from .damier import *
from .ai_pawn import *
from .ai_knight import *
from .ai_queen import *
from .ai_king import *
from .ai_bishop import *
from .ai_tower import *
from .pawn import *
from .knight import *
from .queen import *
from .king import *
from .bishop import *
from .tower import *